### ISSUE TITLE
[FEATURE REQUEST] Make the Action Faster

### ISSUE THREAD

**Issue by aditya-mitra** [darrenjennings/algolia-docsearch-action#2]
First of all, excellent action for uploading search indexes to algolia!
I am using it it for a [documentation repo](https://github.com/uinstinct/important_cp).

Currently, the action is taking around *1.5 mins* to complete which is according to me okay but can be certainly improved.

![on github actions](https://user-images.githubusercontent.com/55396651/120176312-c1be0880-c224-11eb-8390-5280327659e0.png)

If we can speed up the build using caching, it would be awesome.
I found one example: https://pythonspeed.com/articles/speeding-up-docker-ci/

If this idea can work out, I am willing to collaborate.
Thank you.

**Comment by darrenjennings** [comment]
> If this idea can work out, I am willing to collaborate.

I would gladly accept a PR!

> First of all, excellent action for uploading search indexes to algolia!

thank you!

**Comment by aditya-mitra** [comment]
Okay, I will try to make a pull request within the next 2 weeks.
